# Generated by Django 3.0.3 on 2020-06-30 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('DJ Sanghvi College of Engineering', 'DJ Sanghvi College of Engineering'), ('KJ Somaiya College of Engineering', 'KJ Somaiya College of Engineering'), ('Thadomal Sahani College of Engineering', 'Thadomal Sahani College of Engineering'), ('Thakur College of Engineering', 'Thakur College of Engineering'), ('Atharva College of Engineering', 'Atharva College of Engineering'), ('Sardar Patel College of Engineering', 'Sardar Patel College of Engineering'), ('VJTI College of Engineering', 'VJTI College of Engineering')], default='', max_length=300)),
                ('branch', models.CharField(blank='true', choices=[('Computer', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ELEX', 'ELEX'), ('Chemical', 'Chemical'), ('Production', 'Production'), ('Bio Med', 'Bio Med')], max_length=300, null='true')),
                ('designation', models.CharField(choices=[('Senior Librarian', 'Senior Librarian'), ('Principal', 'Principal'), ('Canteen Owner', 'Canteen Owner'), ('Security Head', 'Security Head'), ('HOD', 'HOD'), ('Vice-Principal', 'Vice-Principal')], default='', max_length=20)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_heading', models.CharField(default='', max_length=300)),
                ('complain_content', models.TextField()),
                ('college', models.CharField(choices=[('DJ Sanghvi College of Engineering', 'DJ Sanghvi College of Engineering'), ('KJ Somaiya College of Engineering', 'KJ Somaiya College of Engineering'), ('Thadomal Sahani College of Engineering', 'Thadomal Sahani College of Engineering'), ('Thakur College of Engineering', 'Thakur College of Engineering'), ('Atharva College of Engineering', 'Atharva College of Engineering'), ('Sardar Patel College of Engineering', 'Sardar Patel College of Engineering'), ('VJTI College of Engineering', 'VJTI College of Engineering')], default='', max_length=300)),
                ('branch', models.CharField(blank='true', choices=[('Computer', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ELEX', 'ELEX'), ('Chemical', 'Chemical'), ('Production', 'Production'), ('Bio Med', 'Bio Med')], max_length=300, null='true')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_resolved', models.CharField(default='', max_length=40)),
                ('status', models.CharField(choices=[('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Viewed', 'Viewed'), ('Solved', 'Solved')], default='Pending', max_length=20)),
                ('response', models.TextField(default='')),
                ('related_to', models.CharField(choices=[('Management', 'Management'), ('Faculty', 'Faculty'), ('Canteen', 'Canteen'), ('Library', 'Library'), ('Security', 'Security')], default='', max_length=20, verbose_name='Complain Related to')),
                ('transfer', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(related_name='complain', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.Admin')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('DJ Sanghvi College of Engineering', 'DJ Sanghvi College of Engineering'), ('KJ Somaiya College of Engineering', 'KJ Somaiya College of Engineering'), ('Thadomal Sahani College of Engineering', 'Thadomal Sahani College of Engineering'), ('Thakur College of Engineering', 'Thakur College of Engineering'), ('Atharva College of Engineering', 'Atharva College of Engineering'), ('Sardar Patel College of Engineering', 'Sardar Patel College of Engineering'), ('VJTI College of Engineering', 'VJTI College of Engineering')], default='', max_length=300)),
                ('branch', models.CharField(choices=[('Computer', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ELEX', 'ELEX'), ('Chemical', 'Chemical'), ('Production', 'Production'), ('Bio Med', 'Bio Med')], default='', max_length=300)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='complain', to='grievance.Complain')),
                ('liker', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='grievance.Student')),
            ],
        ),
        migrations.AddField(
            model_name='complain',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.Student'),
        ),
    ]
