# Generated by Django 3.0.3 on 2020-05-15 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('DJ Sanghvi College of Engineering', 'DJ Sanghvi College of Engineering'), ('KJ Somaiya College of Engineering', 'KJ Somaiya College of Engineering'), ('Thadomal Sahani College of Engineering', 'Thadomal Sahani College of Engineering'), ('Thakur College of Engineering', 'Thakur College of Engineering'), ('Atharva College of Engineering', 'Atharva College of Engineering'), ('Sardar Patel College of Engineering', 'Sardar Patel College of Engineering'), ('VJTI College of Engineering', 'VJTI College of Engineering')], default='', max_length=300)),
                ('branch', models.CharField(blank='true', choices=[('Computer', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ELEX', 'ELEX'), ('Chemical', 'Chemical'), ('Production', 'Production'), ('Bio Med', 'Bio Med')], max_length=300, null='true')),
                ('designation', models.CharField(choices=[('Canteen Owner', 'Canteen Owner'), ('Senior Librarian', 'Senior Librarian'), ('Principal', 'Principal'), ('HOD', 'HOD'), ('Vice-Principal', 'Vice-Principal'), ('Security Head', 'Security Head')], default='', max_length=20)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('DJ Sanghvi College of Engineering', 'DJ Sanghvi College of Engineering'), ('KJ Somaiya College of Engineering', 'KJ Somaiya College of Engineering'), ('Thadomal Sahani College of Engineering', 'Thadomal Sahani College of Engineering'), ('Thakur College of Engineering', 'Thakur College of Engineering'), ('Atharva College of Engineering', 'Atharva College of Engineering'), ('Sardar Patel College of Engineering', 'Sardar Patel College of Engineering'), ('VJTI College of Engineering', 'VJTI College of Engineering')], default='', max_length=300)),
                ('branch', models.CharField(choices=[('Computer', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ELEX', 'ELEX'), ('Chemical', 'Chemical'), ('Production', 'Production'), ('Bio Med', 'Bio Med')], default='', max_length=300)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_heading', models.CharField(default='', max_length=300)),
                ('complain_content', models.TextField()),
                ('college', models.CharField(choices=[('DJ Sanghvi College of Engineering', 'DJ Sanghvi College of Engineering'), ('KJ Somaiya College of Engineering', 'KJ Somaiya College of Engineering'), ('Thadomal Sahani College of Engineering', 'Thadomal Sahani College of Engineering'), ('Thakur College of Engineering', 'Thakur College of Engineering'), ('Atharva College of Engineering', 'Atharva College of Engineering'), ('Sardar Patel College of Engineering', 'Sardar Patel College of Engineering'), ('VJTI College of Engineering', 'VJTI College of Engineering')], default='', max_length=300)),
                ('branch', models.CharField(blank='true', choices=[('Computer', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ELEX', 'ELEX'), ('Chemical', 'Chemical'), ('Production', 'Production'), ('Bio Med', 'Bio Med'), ('College Staff', 'College Staff')], max_length=300, null='true')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Viewed', 'Viewed'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Solved', 'Solved')], default='Pending', max_length=10)),
                ('response', models.TextField(default='')),
                ('related_to', models.CharField(choices=[('Management', 'Management'), ('Faculty', 'Faculty'), ('Library', 'Library'), ('Security', 'Security')], default='', max_length=20, verbose_name='Complain Related to')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.Admin')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.Student')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
