# Generated by Django 3.0.6 on 2020-07-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Principal', 'Principal'), ('HOD', 'HOD'), ('Senior Librarian', 'Senior Librarian'), ('Canteen Owner', 'Canteen Owner'), ('Vice-Principal', 'Vice-Principal'), ('Security Head', 'Security Head')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Library', 'Library'), ('Canteen', 'Canteen'), ('Security', 'Security'), ('Management', 'Management')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Solved', 'Solved'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Viewed', 'Viewed')], default='Pending', max_length=20),
        ),
    ]
