# Generated by Django 3.0.3 on 2020-05-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0002_auto_20200515_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Canteen Owner', 'Canteen Owner'), ('Principal', 'Principal'), ('Security Head', 'Security Head'), ('Vice-Principal', 'Vice-Principal'), ('Senior Librarian', 'Senior Librarian'), ('HOD', 'HOD')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Library', 'Library'), ('Security', 'Security'), ('Management', 'Management')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Rejected', 'Rejected'), ('Viewed', 'Viewed'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
