# Generated by Django 3.0.6 on 2020-07-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0002_auto_20200704_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Canteen Owner', 'Canteen Owner'), ('Vice-Principal', 'Vice-Principal'), ('HOD', 'HOD'), ('Principal', 'Principal'), ('Security Head', 'Security Head'), ('Senior Librarian', 'Senior Librarian')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Security', 'Security'), ('Management', 'Management'), ('Canteen', 'Canteen'), ('Library', 'Library'), ('Faculty', 'Faculty')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Pending', 'Pending'), ('Viewed', 'Viewed'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress')], default='Pending', max_length=20),
        ),
    ]
