# Generated by Django 2.2 on 2020-05-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0003_auto_20200516_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Senior Librarian', 'Senior Librarian'), ('Vice-Principal', 'Vice-Principal'), ('Principal', 'Principal'), ('Canteen Owner', 'Canteen Owner'), ('Security Head', 'Security Head'), ('HOD', 'HOD')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='branch',
            field=models.CharField(blank='true', choices=[('Computer', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ELEX', 'ELEX'), ('Chemical', 'Chemical'), ('Production', 'Production'), ('Bio Med', 'Bio Med')], max_length=300, null='true'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Management', 'Management'), ('Library', 'Library'), ('Faculty', 'Faculty'), ('Canteen', 'Canteen'), ('Security', 'Security')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Viewed', 'Viewed'), ('Rejected', 'Rejected'), ('Solved', 'Solved'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
