# Generated by Django 3.0.6 on 2020-07-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0003_auto_20200704_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='image',
        ),
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Canteen Owner', 'Canteen Owner'), ('Vice-Principal', 'Vice-Principal'), ('HOD', 'HOD'), ('Security Head', 'Security Head'), ('Senior Librarian', 'Senior Librarian')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Canteen', 'Canteen'), ('Library', 'Library'), ('Management', 'Management'), ('Security', 'Security')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Viewed', 'Viewed'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Rejected', 'Rejected'), ('Solved', 'Solved')], default='Pending', max_length=20),
        ),
    ]
