# Generated by Django 4.1.2 on 2022-10-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0005_auto_20200707_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Vice-Principal', 'Vice-Principal'), ('Senior Librarian', 'Senior Librarian'), ('Security Head', 'Security Head'), ('Canteen Owner', 'Canteen Owner'), ('Principal', 'Principal')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Library', 'Library'), ('Canteen', 'Canteen'), ('Faculty', 'Faculty'), ('Management', 'Management'), ('Security', 'Security')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('In Progress', 'In Progress'), ('Viewed', 'Viewed'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
