# Generated by Django 4.1.2 on 2022-10-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0006_alter_admin_designation_alter_complain_related_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Canteen Owner', 'Canteen Owner'), ('Senior Librarian', 'Senior Librarian'), ('Principal', 'Principal'), ('HOD', 'HOD'), ('Vice-Principal', 'Vice-Principal'), ('Security Head', 'Security Head')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Viewed', 'Viewed'), ('Rejected', 'Rejected'), ('Solved', 'Solved')], default='Pending', max_length=20),
        ),
    ]
