# Generated by Django 4.1.2 on 2022-10-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0007_contact_alter_admin_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Vice-Principal', 'Vice-Principal'), ('Senior Librarian', 'Senior Librarian'), ('Security Head', 'Security Head'), ('Canteen Owner', 'Canteen Owner'), ('HOD', 'HOD')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('Library', 'Library'), ('Security', 'Security'), ('Faculty', 'Faculty'), ('Management', 'Management')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Viewed', 'Viewed'), ('In Progress', 'In Progress'), ('Solved', 'Solved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
