# Generated by Django 3.2.15 on 2024-10-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0009_alter_admin_designation_alter_complain_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Vice-Principal', 'Vice-Principal'), ('Senior Librarian', 'Senior Librarian'), ('HOD', 'HOD'), ('Principal', 'Principal'), ('Canteen Owner', 'Canteen Owner'), ('Security Head', 'Security Head')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Management', 'Management'), ('Canteen', 'Canteen'), ('Library', 'Library'), ('Faculty', 'Faculty'), ('Security', 'Security')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Solved', 'Solved'), ('Viewed', 'Viewed')], default='Pending', max_length=20),
        ),
    ]
